# Generated by Django 3.2 on 2021-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_plane_id', models.IntegerField(help_text='测试计划id', verbose_name='测试计划id')),
                ('case_name', models.CharField(help_text='用例名称', max_length=50, verbose_name='用例名称')),
                ('case_description', models.CharField(help_text='用例描述', max_length=500, null=True, verbose_name='用例描述')),
                ('host', models.CharField(help_text='接口host', max_length=50, null=True, verbose_name='接口host')),
                ('api', models.CharField(help_text='接口地址', max_length=100, null=True, verbose_name='接口地址')),
                ('request_method', models.CharField(help_text='请求方式;eg:get', max_length=6, verbose_name='请求方式;eg:get')),
                ('request_type', models.CharField(help_text='请求类型;eg:post请求类型的x-www-from-urlencoded', max_length=50, null=True, verbose_name='请求类型;eg:post请求类型的x-www-from-urlencoded')),
                ('data', models.CharField(help_text='请求数据', max_length=500, null=True, verbose_name='请求数据')),
                ('result', models.CharField(help_text="断言（预期结果）；字典形式存放，eg：{'code':200,'msg':'成功'}", max_length=200, verbose_name="断言（预期结果）；字典形式存放，eg：{'code':200,'msg':'成功'}")),
                ('creator', models.CharField(help_text='创建人', max_length=10, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_enable', models.CharField(default='1', help_text='是否启用；默认为1；1：启用，0：不启用', max_length=1, verbose_name='是否启用；1：启用，0：不启用')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.CharField(default='0', help_text='是否删除；默认为0；1：删除，0：不删除', max_length=1, verbose_name='是否删除；1：删除，0：不删除')),
            ],
            options={
                'verbose_name': '测试用例表',
                'db_table': 'TestCase',
            },
        ),
        migrations.CreateModel(
            name='TestPlane',
            fields=[
                ('id', models.AutoField(help_text='测试计划id', primary_key=True, serialize=False, verbose_name='测试计划id')),
                ('test_plane', models.CharField(help_text='测试计划名称', max_length=20, verbose_name='测试计划名称')),
                ('test_plane_description', models.CharField(help_text='测试计划描述', max_length=100, null=True, verbose_name='测试计划描述')),
                ('creator', models.CharField(help_text='创建人', max_length=10, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_show', models.CharField(default='0', help_text='其余人是否可见,默认为0；0：不可见，1：可见', max_length=1, verbose_name='其余人是否可见,默认为0；0：不可见，1：可见')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_enable', models.CharField(default='1', help_text='是否启用；1：启用，0：不启用', max_length=1, verbose_name='是否启用；1：启用，0：不启用')),
                ('is_delete', models.CharField(default='0', help_text='是否删除；1：删除，0：不删除', max_length=1, verbose_name='是否删除；1：删除，0：不删除')),
            ],
            options={
                'verbose_name': '测试计划表',
                'db_table': 'TestPlane',
            },
        ),
        migrations.CreateModel(
            name='TestPlaneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_plane_id', models.IntegerField(verbose_name='测试计划id')),
                ('env', models.CharField(default='qa', help_text='用例执行环境，默认qa；qa：测试环境，release：线上环境', max_length=10, verbose_name='用例执行环境，qa：测试环境，release：线上环境')),
                ('test_global', models.CharField(help_text='当前计划全局变量，以字典形式存放；eg：{"host1":"www",}', max_length=500, null=True, verbose_name='当前计划全局变量，以字典形式存放；eg：{"host1":"www",}')),
                ('login_info', models.CharField(help_text='存放接口验证的token、session、cookie等验证信息', max_length=200, null=True, verbose_name='存放接口验证的token、session、cookie等验证信息')),
            ],
            options={
                'verbose_name': '测试计划信息表',
                'db_table': 'TestPlaneInfo',
            },
        ),
    ]
